// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDgUGBjKyW7ASuGCJF7eXnBz-jflUIyk',
    appId: '1:698859470882:web:581339a702b6f686ff4a7b',
    messagingSenderId: '698859470882',
    projectId: 'habit-track-6d4ba',
    authDomain: 'habit-track-6d4ba.firebaseapp.com',
    storageBucket: 'habit-track-6d4ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmTVr5UVzABPRmmvQGW3pKrKuoQCrH1M',
    appId: '1:698859470882:android:92596b586fa0369fff4a7b',
    messagingSenderId: '698859470882',
    projectId: 'habit-track-6d4ba',
    storageBucket: 'habit-track-6d4ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxOtYYjHpy3ACK7f6yoGLTTGC5Mtt2X4',
    appId: '1:698859470882:ios:ff98b6356e168078ff4a7b',
    messagingSenderId: '698859470882',
    projectId: 'habit-track-6d4ba',
    storageBucket: 'habit-track-6d4ba.appspot.com',
    iosBundleId: 'com.example.habitTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxOtYYjHpy3ACK7f6yoGLTTGC5Mtt2X4',
    appId: '1:698859470882:ios:ff98b6356e168078ff4a7b',
    messagingSenderId: '698859470882',
    projectId: 'habit-track-6d4ba',
    storageBucket: 'habit-track-6d4ba.appspot.com',
    iosBundleId: 'com.example.habitTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeDgUGBjKyW7ASuGCJF7eXnBz-jflUIyk',
    appId: '1:698859470882:web:2d920b0097be1afaff4a7b',
    messagingSenderId: '698859470882',
    projectId: 'habit-track-6d4ba',
    authDomain: 'habit-track-6d4ba.firebaseapp.com',
    storageBucket: 'habit-track-6d4ba.appspot.com',
  );
}
